from PyQt5.QtWidgets import QApplication,QWidget,QPushButton,QVBoxLayout
app = QApplication([])
app.setStyle('Windows')
window = QWidget()
layout = QVBoxLayout()
layout.addWidget(QPushButton('top'))
layout.addWidget(QPushButton('bottom'))
window.setLayout(layout)
window.show()
app.exec_()
